name: Lint and test workflows
run-name: Workflow linting and testing
on:
  push:
    branches:
      - '*'
      - '!master'
jobs:
  wdl-ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: wdl-ci
        uses: ./
        with:
          wallet-url: ${{ secrets.WALLET_URL }}
          wallet-client-id: ${{ secrets.WALLET_CLIENT_ID }}
          wallet-client-secret: ${{ secrets.WALLET_CLIENT_SECRET }}
          workbench-namespace: ${{ secrets.WORKBENCH_NAMESPACE }}
          workbench-ewes-url: ${{ secrets.WORKBENCH_EWES_URL }}
          workbench-workflow-service-url:  ${{ secrets.WORKBENCH_WORKFLOW_SERVICE_URL }}
          workbench-ewes-refresh-token: ${{ secrets.WORKBENCH_EWES_REFRESH_TOKEN }}
          workbench-workflow-service-refresh-token: ${{ secrets.WORKBENCH_WORKFLOW_SERVICE_REFRESH_TOKEN }}
